add meta data for content type
luchiniatwork/contentful pull request #8
Opened 2018-11-09 21:48 UTC by sashary

2018-11-10 03:23 UTC, luchiniatwork requested changes
Besides the meta comment, I think we should also add this to the documentation (readme) since it is a new feature that _is_ very useful.

2018-11-10 03:23 UTC, luchiniatwork commented on src/cljc/contentql/core.cljc
> +    (merge ^{:content-type
Why did you merge it as a meta here? This will probably meta tag the returning id... I'm a bit confused... could the `^` be a typo? Did this work?

2018-11-11 22:53 UTC, delfes commented on src/cljc/contentql/core.cljc
> +    (merge ^{:content-type
This was an idea to keep real data separated from meta information. If this sounds good, maybe we could use `with-meta` (https://clojuredocs.org/clojure.core/with-meta).

2018-11-15 18:46 UTC, luchiniatwork approved these changes

2018-11-15 18:46 UTC, merged